/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joao5472_luiz5463;

import JavaDB.Banco;
import DBConexao.Conexao;
import java.awt.Color;
import Classes.Agenda;
import Classes.deletarContato;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class Login extends javax.swing.JFrame {
    String  texto, numero, nick, user, email;
    String Usuario = "";
    DefaultListModel lista;
    int index = 0;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        texto = "0123456789!@#$%¨&*()_-+=§|,.<>;:/?°]}º[{ª'`";
        numero = "0123456789";
        nick = "!@#$%¨&*()_-+=§|,.´`<>;:/?°]}º[{ª'`";
        user = "!@#$%¨&*()-+=§|,.~´`<>;:/?°]}º[{ª'`";
        lista = new DefaultListModel();
        lstContato.setModel(lista);
        btnContato_Atualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCadastro = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        btnPesquisar_Contato = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtContato_Pesquisa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        rdbResidencial = new javax.swing.JRadioButton();
        rdbCelular = new javax.swing.JRadioButton();
        btnCadastrar_Contato = new javax.swing.JButton();
        txtTelefone_Cadastro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDDD_Cadastro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome_Cadastro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstContato = new javax.swing.JList<>();
        btnExcluir_Contato = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTipoContato = new javax.swing.JLabel();
        btnLimpar_Pesquisa = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jAtualizarContatos = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        btnRetornarCadastro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscar_Atualizar = new javax.swing.JTextField();
        btnBuscar_Atualizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtDDD_Atualizar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelefone_Atualizar = new javax.swing.JTextField();
        btnContato_Atualizar = new javax.swing.JButton();
        rdbCelular_Atualizar = new javax.swing.JRadioButton();
        rdbResidencial_Atualizar = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario_Login = new javax.swing.JTextField();
        btnLogar = new javax.swing.JButton();
        txtSenha_Login = new javax.swing.JPasswordField();

        btnPesquisar_Contato.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPesquisar_Contato.setText("Pesquisar");
        btnPesquisar_Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar_ContatoActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAtualizar.setText("Atualizar Dados de Contato");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Digite o nome do contato:");

        txtContato_Pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContato_PesquisaKeyTyped(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Tipo:");

        rdbResidencial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdbResidencial.setText("Residencial");
        rdbResidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbResidencialActionPerformed(evt);
            }
        });

        rdbCelular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdbCelular.setText("Móvel");
        rdbCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCelularActionPerformed(evt);
            }
        });

        btnCadastrar_Contato.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadastrar_Contato.setText("Cadastrar Contato");
        btnCadastrar_Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar_ContatoActionPerformed(evt);
            }
        });

        txtTelefone_Cadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefone_CadastroKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Telefone:");

        txtDDD_Cadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDDD_CadastroKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("DDD:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Nome Completo:");

        txtNome_Cadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNome_CadastroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome_Cadastro))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdbResidencial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCadastrar_Contato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDDD_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefone_Cadastro)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNome_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDDD_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtTelefone_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(rdbResidencial)
                    .addComponent(rdbCelular)
                    .addComponent(btnCadastrar_Contato, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lstContato.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lstContato.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstContatoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstContato);

        btnExcluir_Contato.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExcluir_Contato.setText("Excluir Contato");
        btnExcluir_Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir_ContatoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Nome:");

        lblNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Telefone:");

        lblTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Tipo de contato:");

        lblTipoContato.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnLimpar_Pesquisa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimpar_Pesquisa.setText("Limpar");
        btnLimpar_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar_PesquisaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel7.setText("Agenda");

        btnLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContato_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar_Contato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipoContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnExcluir_Contato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpar_Pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtContato_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar_Contato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13)
                        .addGap(6, 6, 6)
                        .addComponent(lblTipoContato, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnExcluir_Contato)
                        .addGap(9, 9, 9)
                        .addComponent(btnLimpar_Pesquisa))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        javax.swing.GroupLayout jCadastroLayout = new javax.swing.GroupLayout(jCadastro.getContentPane());
        jCadastro.getContentPane().setLayout(jCadastroLayout);
        jCadastroLayout.setHorizontalGroup(
            jCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCadastroLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jCadastroLayout.setVerticalGroup(
            jCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnRetornarCadastro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRetornarCadastro.setText("Retornar");
        btnRetornarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarCadastroActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel8.setText("Modificar Dados");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Digite o nome do contato:");

        txtBuscar_Atualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscar_AtualizarKeyTyped(evt);
            }
        });

        btnBuscar_Atualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscar_Atualizar.setText("Buscar");
        btnBuscar_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar_AtualizarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("DDD:");

        txtDDD_Atualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDDD_AtualizarKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Telefone:");

        txtTelefone_Atualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefone_AtualizarKeyTyped(evt);
            }
        });

        btnContato_Atualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnContato_Atualizar.setText("Atualizar Contato");
        btnContato_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContato_AtualizarActionPerformed(evt);
            }
        });

        rdbCelular_Atualizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdbCelular_Atualizar.setText("Móvel");
        rdbCelular_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCelular_AtualizarActionPerformed(evt);
            }
        });

        rdbResidencial_Atualizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdbResidencial_Atualizar.setText("Residencial");
        rdbResidencial_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbResidencial_AtualizarActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Tipo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbResidencial_Atualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbCelular_Atualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnContato_Atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDDD_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelefone_Atualizar)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDDD_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtTelefone_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(rdbResidencial_Atualizar)
                        .addComponent(rdbCelular_Atualizar))
                    .addComponent(btnContato_Atualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar_Atualizar)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRetornarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscar_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar_Atualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRetornarCadastro)
                .addContainerGap())
        );

        javax.swing.GroupLayout jAtualizarContatosLayout = new javax.swing.GroupLayout(jAtualizarContatos.getContentPane());
        jAtualizarContatos.getContentPane().setLayout(jAtualizarContatosLayout);
        jAtualizarContatosLayout.setHorizontalGroup(
            jAtualizarContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jAtualizarContatosLayout.setVerticalGroup(
            jAtualizarContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Usúario:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Senha:");

        txtUsuario_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuario_LoginActionPerformed(evt);
            }
        });
        txtUsuario_Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuario_LoginKeyTyped(evt);
            }
        });

        btnLogar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnLogar.setText("Confirmar");
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });

        txtSenha_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenha_LoginActionPerformed(evt);
            }
        });
        txtSenha_Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSenha_LoginKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogar, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario_Login)
                            .addComponent(txtSenha_Login))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSenha_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuario_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuario_LoginActionPerformed

    }//GEN-LAST:event_txtUsuario_LoginActionPerformed

    private void txtUsuario_LoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuario_LoginKeyTyped
        if (user.contains(""+evt.getKeyChar()))
        {
            evt.consume();
        }
        if (txtUsuario_Login.getText().length() > 24)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtUsuario_LoginKeyTyped

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        boolean validarUsuario = false, validarSenha = false;

        Conexao con;

        try
        {
            con = new Conexao();
            con.Conectar();

            if (txtUsuario_Login.getText().equals("") || txtSenha_Login.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            }
            else
            {
                ResultSet usuario = con.Consultar("select cd_usuario from tb_usuario");

                while(usuario.next())
                {
                    String user = usuario.getString("cd_usuario");
                    if (user.equals(txtUsuario_Login.getText()))
                    {
                        validarUsuario = true;
                        break;
                    }
                }

                ResultSet senha = con.Consultar("select cd_senha from tb_usuario");
                while(senha.next())
                {
                    String password = senha.getString("cd_senha");
                    if (password.equals(txtSenha_Login.getText()))
                    {
                        validarSenha = true;
                        break;
                    }
                }

                if (validarSenha == true && validarUsuario == true)
                {
                    JOptionPane.showMessageDialog(null, "Login realizado com sucesso.");
                    Usuario = txtUsuario_Login.getText();
                    txtUsuario_Login.setText("");
                    txtSenha_Login.setText("");
                    this.setVisible(false);
                    jCadastro.setSize(492, 585);
                    jCadastro.setTitle("Cadastro de Usuarios");
                    jCadastro.setModal(true);
                    jCadastro.setLocationRelativeTo(null);
                    jCadastro.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Digite os dados de login corretamente.");
                }
            }
        }
        catch(ClassNotFoundException ex)
        {
            Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(NullPointerException ex)
        {
            Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogarActionPerformed

    private void txtSenha_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenha_LoginActionPerformed

    }//GEN-LAST:event_txtSenha_LoginActionPerformed

    private void txtSenha_LoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenha_LoginKeyTyped
        if (txtSenha_Login.getText().length() > 49)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtSenha_LoginKeyTyped

    private void txtNome_CadastroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNome_CadastroKeyTyped
        if (texto.contains(""+evt.getKeyChar()))
        {
            evt.consume();
        }
        if (txtNome_Cadastro.getText().length() > 39)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNome_CadastroKeyTyped

    private void txtDDD_CadastroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDDD_CadastroKeyTyped
        if (!numero.contains(""+evt.getKeyChar()))
        {
            evt.consume();
        }
        if (txtDDD_Cadastro.getText().length() > 2)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtDDD_CadastroKeyTyped

    private void txtTelefone_CadastroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefone_CadastroKeyTyped
        if (!numero.contains(""+evt.getKeyChar()))
        {
            evt.consume();
        }
        if (txtTelefone_Cadastro.getText().length() > 8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefone_CadastroKeyTyped

    private void rdbResidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbResidencialActionPerformed
        if (rdbResidencial.isSelected() == true)
        {
            rdbCelular.setSelected(false);
        }
    }//GEN-LAST:event_rdbResidencialActionPerformed

    private void rdbCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCelularActionPerformed
        if (rdbCelular.isSelected() == true)
        {
            rdbResidencial.setSelected(false);
        }
    }//GEN-LAST:event_rdbCelularActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        jCadastro.setVisible(false);
        this.setSize(360,260);
        this.setTitle("Login");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCadastrar_ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar_ContatoActionPerformed
        /*Conexao con;
        
        try
        {
            con = new Conexao();
            con.Conectar();*/
            
            if (txtNome_Cadastro.getText().equals("") || txtDDD_Cadastro.getText().equals("") || txtTelefone_Cadastro.getText().equals("") || rdbResidencial.isSelected() == false && rdbCelular.isSelected() == false)
            {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            }
            else
            {
                boolean valiTel = false;
                char TipoTel = ' ';
                if (txtTelefone_Cadastro.getText().length() < 8)
                {
                    txtTelefone_Cadastro.setBackground(Color.red);
                }
                else
                {
                    txtTelefone_Cadastro.setBackground(Color.white);
                    valiTel = true;
                }
                
                if (valiTel == true)
                {
                    if (rdbResidencial.isSelected() == true)
                    {
                        TipoTel = 'R';
                    }
                    else if (rdbCelular.isSelected() == true)
                    {
                        TipoTel = 'M';
                    }
                    
                    //con.Executar("INSERT INTO tb_contato (nm_contato, cd_estado, cd_telefone, ic_tipoTel, cd_usuario) VALUES ('"+txtNome_Cadastro.getText()+"', "+txtDDD_Cadastro.getText()+", '"+txtTelefone_Cadastro.getText()+"', '"+TipoTel+"', '"+Usuario+"')");
                    JOptionPane.showMessageDialog(null, "Contato adicionado com sucesso.");
                    txtNome_Cadastro.setText("");
                    txtDDD_Cadastro.setText("");
                    txtTelefone_Cadastro.setText("");
                    rdbResidencial.setSelected(false);
                    rdbCelular.setSelected(false);
                }
            }
        /*}
        catch(ClassNotFoundException ex)
        {
            Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(NullPointerException ex)
        {
            Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnCadastrar_ContatoActionPerformed

    private void btnPesquisar_ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar_ContatoActionPerformed
        if (txtContato_Pesquisa.getText().equals(""))
        {
             JOptionPane.showMessageDialog(null, "Preencha o campo em branco");
        }
        else
        {
            lista.removeAllElements();
            Conexao con;
            try
            {
                con = new Conexao();
                con.Conectar();
                ResultSet Registros = con.Consultar("select nm_contato from tb_contato");
                while(Registros.next())
                {
                    String Tel = Registros.getString("cd_telefone");
                    String Nome = Registros.getString("nm_contato");
                    if (Nome.toUpperCase().contains(txtContato_Pesquisa.getText().toUpperCase()))
                    {
                        lista.addElement(Nome + " - " + Tel);
                    }
                }
            }  
            catch(ClassNotFoundException ex)
            {
                Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch(SQLException ex)
            {
                Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch(NullPointerException ex)
            {
                Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
            }           
            txtContato_Pesquisa.setText(null);
        }
    }//GEN-LAST:event_btnPesquisar_ContatoActionPerformed

    private void txtContato_PesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContato_PesquisaKeyTyped
        if (texto.contains(""+evt.getKeyChar()))
        {
            evt.consume();
        }
        if (txtContato_Pesquisa.getText().length() > 39)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtContato_PesquisaKeyTyped

    private void lstContatoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstContatoValueChanged
        if (lstContato.getSelectedIndex() != -1)
        {
            String[] n = new String[2];
            String tipoContato = "";
            n = lstContato.getSelectedValue().toString().split(" - ", 2);
            
            Classes.Agenda agenda = new Agenda();
            agenda.setNome(n[1].toString());
            lblNome.setText(n[0]);
            lblTelefone.setText(n[1]);
            lblTipoContato.setText(agenda.TipoContato());
            index = lstContato.getSelectedIndex();
            lstContato.setSelectedIndex(-1);
        }
        else
        {
            lblNome.setText(null);
            lblTelefone.setText(null);
            lblTipoContato.setText(null);
        }
    }//GEN-LAST:event_lstContatoValueChanged

    private void btnExcluir_ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir_ContatoActionPerformed
        if (lstContato.getSelectedIndex() >= 0)
        {
            if (JOptionPane.showConfirmDialog(null, "Você deseja mesmo deletar o contato "+lblNome.getText(), "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION)
            {
                Classes.deletarContato deletar = new deletarContato();
                deletar.setParametro(lblNome.getText().toString());
                if (deletar.ValiDel())
                {
                    deletar.Deletar();
                    JOptionPane.showMessageDialog(null, "Contato deletado com sucesso.");
                    lista.removeElementAt(index);
                    lblNome.setText(null);
                    lblTelefone.setText(null);
                    lblTipoContato.setText(null);
                    lstContato.clearSelection();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Nome inválido!");;
                }
            }    
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione um contato da lista!");
        }
    }//GEN-LAST:event_btnExcluir_ContatoActionPerformed

    private void btnLimpar_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar_PesquisaActionPerformed
        lstContato.clearSelection();
        lista.removeAllElements();
        Conexao con;
        try
        {
            con = new Conexao();
            con.Conectar();
            ResultSet Registros = con.Consultar("select nm_contato, cd_telefone from tb_contato");
            while(Registros.next())
            {
                String t = Registros.getString("cd_telefone");
                String n = Registros.getString("nm_contato");
                lista.addElement(n + " - " + t);
            }
        }
        catch(ClassNotFoundException ex)
        {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(NullPointerException ex)
        {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLimpar_PesquisaActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        txtNome_Cadastro.setText("");
        txtDDD_Cadastro.setText("");
        txtTelefone_Cadastro.setText("");
        rdbResidencial.setSelected(false);
        rdbCelular.setSelected(false);
        jCadastro.setVisible(false);
        jAtualizarContatos.setSize(423, 270);
        jAtualizarContatos.setTitle("Atualizar Dados");
        jAtualizarContatos.setModal(true);
        jAtualizarContatos.setLocationRelativeTo(null);
        jAtualizarContatos.setVisible(true);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnRetornarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarCadastroActionPerformed
        jAtualizarContatos.setVisible(false);
        jCadastro.setSize(492, 585);
        jCadastro.setTitle("Cadastro de Usuarios");
        jCadastro.setModal(true);
        jCadastro.setLocationRelativeTo(null);
        jCadastro.setVisible(true);
        
        txtDDD_Atualizar.setText("");
        txtTelefone_Atualizar.setText("");
        rdbResidencial_Atualizar.setSelected(false);
        rdbCelular_Atualizar.setSelected(false);
        btnContato_Atualizar.setEnabled(false);
        txtBuscar_Atualizar.setText("");
    }//GEN-LAST:event_btnRetornarCadastroActionPerformed

    private void txtBuscar_AtualizarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar_AtualizarKeyTyped
        if (texto.contains(""+evt.getKeyChar()))
        {
            evt.consume();
        }
        if (txtNome_Cadastro.getText().length() > 39)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscar_AtualizarKeyTyped

    private void btnBuscar_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar_AtualizarActionPerformed
        if (txtBuscar_Atualizar.getText().equals(""))
        {
             JOptionPane.showMessageDialog(null, "Preencha o campo em branco");
        }
        else
        {
            Conexao con;
            try
            {
                con = new Conexao();
                con.Conectar();
                ResultSet Registros = con.Consultar("select nm_contato from tb_contato");
                while(Registros.next())
                {
                    String Nome = Registros.getString("nm_contato");
                    if (Nome.toUpperCase().contains(txtBuscar_Atualizar.getText().toUpperCase()))
                    {
                        btnContato_Atualizar.setEnabled(true);
                    }
                }
            }  
            catch(ClassNotFoundException ex)
            {
                Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch(SQLException ex)
            {
                Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch(NullPointerException ex)
            {
                Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
            }           
            txtBuscar_Atualizar.setText(null);
        }
    }//GEN-LAST:event_btnBuscar_AtualizarActionPerformed

    private void txtDDD_AtualizarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDDD_AtualizarKeyTyped
        if (!numero.contains(""+evt.getKeyChar()))
        {
            evt.consume();
        }
        if (txtDDD_Atualizar.getText().length() > 2)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtDDD_AtualizarKeyTyped

    private void txtTelefone_AtualizarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefone_AtualizarKeyTyped
        if (!numero.contains(""+evt.getKeyChar()))
        {
            evt.consume();
        }
        if (txtTelefone_Atualizar.getText().length() > 8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefone_AtualizarKeyTyped

    private void rdbResidencial_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbResidencial_AtualizarActionPerformed
       if (rdbResidencial_Atualizar.isSelected() == true)
        {
            rdbCelular_Atualizar.setSelected(false);
        }
    }//GEN-LAST:event_rdbResidencial_AtualizarActionPerformed

    private void rdbCelular_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCelular_AtualizarActionPerformed
        if (rdbCelular_Atualizar.isSelected() == true)
        {
            rdbResidencial_Atualizar.setSelected(false);
        }
    }//GEN-LAST:event_rdbCelular_AtualizarActionPerformed

    private void btnContato_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContato_AtualizarActionPerformed
        Conexao con;
        
        try
        {
            con = new Conexao();
            con.Conectar();
            
            if (txtDDD_Atualizar.getText().equals("") || txtTelefone_Atualizar.getText().equals("") || rdbResidencial_Atualizar.isSelected() == false && rdbCelular_Atualizar.isSelected() == false)
            {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            }
            else
            {
                boolean valiTel = false;
                char TipoTel = ' ';
                if (txtTelefone_Atualizar.getText().length() < 8)
                {
                    txtTelefone_Atualizar.setBackground(Color.red);
                }
                else
                {
                    txtTelefone_Atualizar.setBackground(Color.white);
                    valiTel = true;
                }
                
                if (valiTel == true)
                {
                    if (rdbResidencial_Atualizar.isSelected() == true)
                    {
                        TipoTel = 'R';
                    }
                    else if (rdbCelular_Atualizar.isSelected() == true)
                    {
                        TipoTel = 'M';
                    }
                    
                    con.Executar("UPDATE tb_contato SET cd_estado = "+txtDDD_Atualizar.getText()+", cd_telefone = '"+txtTelefone_Atualizar.getText()+"', ic_tipoTel = '"+TipoTel+"' WHERE nm_contato = '"+txtBuscar_Atualizar.getText()+"')");
                    JOptionPane.showMessageDialog(null, "Contato atualizado com sucesso.");
                    txtDDD_Atualizar.setText("");
                    txtTelefone_Atualizar.setText("");
                    rdbResidencial_Atualizar.setSelected(false);
                    rdbCelular_Atualizar.setSelected(false);
                    btnContato_Atualizar.setEnabled(false);
                }
            }
        }
        catch(ClassNotFoundException ex)
        {
            Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(NullPointerException ex)
        {
            Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnContato_AtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar_Atualizar;
    private javax.swing.JButton btnCadastrar_Contato;
    private javax.swing.JButton btnContato_Atualizar;
    private javax.swing.JButton btnExcluir_Contato;
    private javax.swing.JButton btnLimpar_Pesquisa;
    private javax.swing.JButton btnLogar;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPesquisar_Contato;
    private javax.swing.JButton btnRetornarCadastro;
    private javax.swing.JDialog jAtualizarContatos;
    private javax.swing.JDialog jCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipoContato;
    private javax.swing.JList<String> lstContato;
    private javax.swing.JRadioButton rdbCelular;
    private javax.swing.JRadioButton rdbCelular_Atualizar;
    private javax.swing.JRadioButton rdbResidencial;
    private javax.swing.JRadioButton rdbResidencial_Atualizar;
    private javax.swing.JTextField txtBuscar_Atualizar;
    private javax.swing.JTextField txtContato_Pesquisa;
    private javax.swing.JTextField txtDDD_Atualizar;
    private javax.swing.JTextField txtDDD_Cadastro;
    private javax.swing.JTextField txtNome_Cadastro;
    private javax.swing.JPasswordField txtSenha_Login;
    private javax.swing.JTextField txtTelefone_Atualizar;
    private javax.swing.JTextField txtTelefone_Cadastro;
    private javax.swing.JTextField txtUsuario_Login;
    // End of variables declaration//GEN-END:variables
}
